### ISSUE TITLE
No results from the functree 2 web

### ISSUE THREAD

**Issue by XXY1** [yamada-lab/functree-ng#11]
Hi,

I am trying to use https://bioviz.tokyo/functree2/analysis/mapping/ with my data, but there was no results coming out. I don't know why. could you please help me have a look what's wrong? Here I attached my data and result page screenshot.

Thank you so much.

[test.txt](https://github.com/yamada-lab/functree-ng/files/3007613/test.txt)
<img width="1266" alt="Screen Shot 2019-03-26 at 8 06 21 PM" src="https://user-images.githubusercontent.com/38745013/54989188-bc8d1f80-5003-11e9-9ba6-0a17a5e93cae.png">

**Comment by omixer** [comment]
Hello, 

To solve you problem please trim the empty column in the input file before submitting it to Functree 2.

sed 's/\t$//' test.txt -i

[test.txt](https://github.com/yamada-lab/functree-ng/files/3008528/test.txt)

Kind regards,
Youssef

**Comment by XXY1** [comment]
Thank you so much. It's working now.
