### ISSUE TITLE
Use data from Ghost/KOfam-KOALA

### ISSUE THREAD

**Issue by nclaesnacw** [yamada-lab/functree-ng#32]
I would like to display the KEGG annotations for strains on the functree KEGG dendrogram (I like it a lot). I get my KEGG annotations from KOfamKOALA (could be GhostKOALA). I can see how the data I get back from the KEGG mapper Pathway and Module (which show the KEGG annotations of my predicted proteins e.g for a genome) might be mapped to the input format for functree/functree-2 with a value based on the number of genes assigned to each KEGG category.
E.g.
KOALA data                                                            Functree input
Carbohydrate metabolism
00010 Glycolysis / Gluconeogenesis (18)   -->      n-map00010 tab v-0.0           
K00134 HPA006_002788                                        n-K00134 tab v-1.0
K00138 HPA006_001058, HPA006_002801            n-K00138 tab v-2.0
K00163 HPA006_001900                                        n-K00163 tab v-1.0
K00174 HPA006_001700                                        n-K00174 tab v-1.0
K00175 HPA006_001701   etc.
But I can't see how to easily achieve that transformation - but neither do I understand, looking at the input data files for Streptomyces Mycobacteria and Ecoli how, or from what data, those values were calculated. My data input would look very different.
Is it possible to add more explanation on how to generate input data? And for me, how to input data for multiple strains as per your Streptomyces/Mycobacteri/Ecoli comparison.
Thanks

**Comment by omixer** [comment]
Thank you for your feedback!

This repo is only for  FuncTree2. Its input data is different from FuncTree version 1. 
In mapping mode, the input data is a plain KO abundance matrix as described in the docs https://bioviz.tokyo/functree2/docs/ How you generate it, depends on your application. In display mode you can pass KEGG Modules and Maps in addition to the KO and FuncTree2 will directly highlight them without any additional mapping.
 
To visualize multiple strains simply add them as columns in the matrix and then you can select which strain to view together once the  viewer is ready.

I hope this helps and if you have question about FuncTree version 1 please check the contact form at https://bioviz.tokyo/functree/about/ 

Best,
Youssef
